### ISSUE TITLE
ibmcom/db2express-c:latest has been moved/taken down

### ISSUE THREAD

**Issue by jhic** [IBM/universal-connector#6]
The docker command refers to "ibmcom/db2express-c:latest" here:

`$ docker run -it -p 50000:50000 -e DB2INST1_PASSWORD=db2inst1-pwd -e LICENSE=accept   -v  $(pwd):/share  ibmcom/db2express-c:latest bash`

but it no longer refers to a docker object. Looks like it was removed a few days ago.

**Comment by feromax** [comment]
yes, I'm finding the same :-/

**Comment by jhic** [comment]
> yes, I'm finding the same :-/

You can sub one of the community db2 instances if you would like. for example, https://hub.docker.com/r/henriquemoreno/db2express-c

note that I cannot vouch for this and ideally IBM would just update the new location for db2express, but in the meantime you can use one of those.

**Comment by feromax** [comment]
Thank you, @jhic.  I noticed that community image and wasn't sure if the image had been modified.  (No `Dockerfile` or associated repo...)

**Comment by devanshah1** [comment]
@jhic @feromax Can use the one at: https://hub.docker.com/_/db2-developer-c-edition

**Comment by jhic** [comment]
Thanks @devanshah1 . Looks like that docker image is going to be sunset in a few weeks and projects should move to https://hub.docker.com/r/ibmcom/db2 @feromax may want to use this one instead.

**Comment by joseaio** [comment]
The image https://hub.docker.com/r/ibmcom/db2 is no longer available...

   Any idea about any Docker Repo that contains IBM/DB2 images?

**Comment by devanshah2** [comment]
@joseaio It looks like the https://hub.docker.com/r/ibmcom/db2 image is still available to use.

<img width="1309" alt="Screen Shot 2020-01-13 at 10 11 32 AM" src="https://user-images.githubusercontent.com/19493874/72266808-1c81a080-35ed-11ea-91ac-e10724c9934d.png">
